EMOJI_SENTIMENT_MAP = {
    "😂": "Hài hước, vui cười chảy nước mắt",
    "👍": "Rất tốt",
    "😍": "Yêu thích quá à",
    "❤": "Trái tim",
    "😭": "Huhu",
    "😁": "Cười tươi",
    "😊": "Hài lòng, vui vẻ",
    "😘": "Nụ hôn",
    "☺": "Nụ cười dễ thương",
    "😋": "Ngon miệng",
    "😆": "Cười vui vẻ",
    "👌": "Được rồi, tốt",
    "😄": "Cười hạnh phúc",
    "😅": "Cười hối hận, xấu hổ",
    "😝": "Mặt xấu, trêu đùa",
    "😢": "Khóc, buồn",
    "😒": "Khó chịu",
    "✔": "Đúng, hoàn thành",
    "👏": "Vỗ tay, chúc mừng",
    "😡": "Giận dữ",
    "😑": "Không cảm xúc, mệt mỏi",
    "😉": "Nháy mắt, tinh nghịch",
    "😤": "Cảm giác bị xúc phạm, giận dữ",
    "😔": "Buồn, thất vọng",
    "😓": "Mệt mỏi, căng thẳng",
    "😜": "Nháy mắt, vui vẻ",
    "😌": "Cảm giác nhẹ nhõm, yên tĩnh",
    "✌": "Hòa bình, chiến thắng",
    "😚": "Nụ hôn gió",
    "💋": "Nụ hôn",
    "😱": "Sợ hãi",
    "😞": "Thất vọng",
    "😰": "Lo lắng",
    "😥": "Buồn bã",
    "😎": "Phong cách, ngầu",
    "😪": "Mệt mỏi, buồn ngủ",
    "👎": "Không tốt, phản đối",
    "♥": "Yêu thương",
    "😏": "Nụ cười gian xảo",
    "😩": "Mệt mỏi, căng thẳng",
    "😛": "Làm mặt xấu, vui vẻ",
    "😠": "Tức giận",
    "😐": "Không cảm xúc, trung lập",
    "😳": "Bối rối, xấu hổ",
    "♡": "Yêu, tình yêu",
    "😀": "Cười tươi, vui vẻ",
    "😣": "Khó chịu, đau đớn",
    "😃": "Cười hạnh phúc",
    "🎉": "Ăn mừng, vui vẻ",
    "😕": "Bối rối",
    "😙": "Nụ hôn",
    "💓": "Trái tim yêu thương",
    "💕": "Yêu thương, ngọt ngào",
    "🎀": "Ruy băng, quà tặng",
    "😖": "Đau đớn, khó chịu",
    "🙈": "Không nhìn, xấu hổ",
    "😫": "Mệt mỏi, kiệt sức",
    "👉": "Chỉ tay",
    "💜": "Tình yêu, ngọt ngào",
    "😬": "Khó chịu, không vui",
    "💗": "Yêu thương, trái tim",
    "😻": "Mèo đáng yêu",
    "🍴": "Dụng cụ ăn uống",
    "💞": "Tình yêu, kết nối",
    "❌": "Không, sai",
    "✨": "Lấp lánh, đẹp",
    "💪": "Sức mạnh",
    "📌": "Ghim, chỉ ra",
    "💖": "Yêu thương",
    "😨": "Sợ hãi",
    "🍫": "Sô cô la",
    "😧": "Sợ hãi, ngạc nhiên",
    "🌸": "Hoa anh đào",
    "😹": "Mèo cười",
    "😿": "Mèo khóc",
    "⭕": "Vòng tròn",
    "😇": "Thiên thần, tốt bụng",
    "🙆": "Đồng ý, hài lòng",
    "🍺": "Bia",
    "😯": "Ngạc nhiên, khó tin",
    "😶": "Im lặng, không nói",
    "🤗": "Ôm ấp, chào đón",
    "🍝": "Mỳ Ý",
    "√": "Đúng, chính xác",
    "🐷": "Con lợn",
    "🏿": "Màu da đen",
    "🏠": "Nhà",
    "👀": "Mắt, nhìn",
    "👻": "Ma",
    "😗": "Môi, nụ hôn",
    "👅": "Lưỡi",
    "🙏": "Cầu nguyện, biết ơn",
    "🍦": "Kem",
    "☕": "Cà phê",
    "💙": "Trái tim xanh",
    "🍕": "Pizza",
    "🍲": "Món ăn",
    "🙄": "Mắt lăn, thất vọng",
    "💰": "Tiền",
    "🎄": "Cây thông Noel",
    "✅": "Đã hoàn thành",
    "💵": "Tiền giấy",
    "🍸": "Cocktail",
    "🌟": "Ngôi sao",
    "🍥": "Chả cá Nhật Bản",
    "☀": "Mặt trời",
    "💔": "Trái tim tan vỡ",
    "💸": "Tiền bay đi",
    "🍧": "Đá bào",
    "🍹": "Cocktail",
    "😵": "Mệt mỏi, chóng mặt",
    "👊": "Đấm",
    "🎊": "Lễ hội, ăn mừng",
    "👄": "Môi",
    "⭐": "Ngôi sao",
    "👆": "Chỉ lên",
    "💢": "Tức giận",
    "❗": "Dấu chấm than",
    "💚": "Trái tim xanh",
    "🤔": "Nghĩ ngợi",
    "🍰": "Bánh ngọt",
    "😷": "Đeo khẩu trang",
    "😲": "Sốc, ngạc nhiên",
    "🎃": "Mặt nạ Halloween",
    "😺": "Mèo dễ thương",
    "⊙": "Biểu tượng đặc biệt",
    "💟": "Trái tim yêu thương",
    "😸": "Mèo cười",
    "🍃": "Lá cây",
    "👱": "Người tóc vàng",
    "➖": "Dấu trừ",
    "💨": "Gió, không khí",
    "🐾": "Dấu chân thú cưng",
    "": "Biểu tượng đặc biệt",
    "🍵": "Trà",
    "💥": "Nổ, vụ nổ",
    "🎶": "Âm nhạc",
    "💦": "Mồ hôi",
    "🖤": "Trái tim đen"
}
